#String
Str="Hello"
print(min(Str))
#Tuple
Tuple=(1,2,3,45,6)
print(min(Tuple))
#List
List=[1,2,3,4,5]
print(min(List))
#Dictionary
Dictionary={"name":"shubham","age":18,"gen":"male"}
print(min(Dictionary))
#Set
Set={1,2,3,4,5}
print(min(Set))