x1=float(input("Enter the value of x1"))
y1=float(input("Enter the value of y1"))
x2=float(input("Enter the value of x2"))
y2=float(input("Enter the value of y2"))
distance=((x2-x1)**2+(y2-y1)**2)**(1/2)
print(distance)